### Importacion de Librerias

In [1]:
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd

# Configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)

Requirement already satisfied: openpyxl in c:\users\yorie\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\yorie\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

### Cargar los datasets desde data/raw

In [2]:
data2023 = pd.read_excel("../data/raw/2023_113_Reporte.xlsx")
data2024 = pd.read_excel("../data/raw/2024_113_Reporte.xlsx")
data2025 = pd.read_excel("../data/raw/2025_113_Reporte.xlsx")

### Agrupar datasets en un diccionario

In [3]:
datasets = {
    "2023": data2023,
    "2024": data2024,
    "2025": data2025
}

### Convertir zscore a número

In [4]:
data2023["zscore_pt"] = data2023["zscore_pt"].str.replace(",", ".").astype(float)

### Revisar rangos de edad y validar

In [5]:
data2023["edad_"].describe()

count    107.000000
mean       2.943925
std        3.012026
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       13.000000
Name: edad_, dtype: float64

In [6]:
data2023[data2023["edad_"] > 5]

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,pri_nom_,seg_nom_,pri_ape_,seg_ape_,tip_ide_,num_ide_,edad_,uni_med_,nacionali_,nombre_nacionalidad,sexo_,iden_gener,otra_ident,orient_sex,otra_orien,cod_pais_o,cod_dpto_o,cod_mun_o,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,lat_dir,long_dir,ocupacion_,tip_ss_,cod_ase_,per_etn_,nom_grupo_,estrato_,gp_discapa,gp_desplaz,gp_migrant,gp_carcela,gp_gestan,sem_ges_,gp_indigen,gp_pobicbf,gp_mad_com,gp_desmovi,gp_psiquia,gp_vic_vio,gp_otros,fuente_,cod_pais_r,cod_dpto_r,cod_mun_r,fec_con_,ini_sin_,tip_cas_,pac_hos_,fec_hos_,con_fin_,fec_def_,ajuste_,telefono_,fecha_nto_,cer_def_,cbmte_,uni_modif,nuni_modif,fec_arc_xl,nom_dil_f_,tel_dil_f_,fec_aju_,nit_upgd,fm_fuerza,fm_unidad,fm_grado,version,pri_nom_ma,seg_nom_ma,pri_ape_ma,seg_ape_ma,tip_ide_ma,num_ide_ma,niv_educat,menores,peso_nac,talla_nac,edad_ges,t_lechem,e_complem,crec_dllo,esq_vac,carne_vac,peso_act,talla_act,per_braqui,res_pr_ape,imc,zscore_pt,clas_peso,zscore_te,clas_talla,edema,delgadez,piel_rese,hiperpigm,cambios_cabello,palidez,ruta_atenc,tipo_manej,diag_medic,estrato_datos_complementarios,nom_eve,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,FechaHora,RegIniFec,vacio
0,113,10/01/2023,2,2023,4484700677,2,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,6,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA TOSPA,NaN,RANCHERIA TOSPA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,10/01/2023,- -,4,2,- -,1,- -,7,3216532684,29/06/2022,NaN,NaN,NaN,NaN,- -,JOSE JAIME ALVAREZ,3005323756,20/02/2024,9001913221,NaN,NaN,NaN,Captura 1.6.31,MAGALIS,NaN,GONZALEZ,IPUANA,CC,27033702,5.0,1,2620.0,47,38.0,10,4,1,1,1,5,60,"11,5",1.0,"13,89",-2.2374,2,"-3,562",1,2,1,2,2,2,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,OUTTAJIAPULEE IPSI,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
3,113,04/10/2023,40,2023,2057000983,5,DWIA,RUKUNGUMU,MEJIA,CRESPO,RC,1063604976,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,SIMONORWA,NaN,SIMONORWA,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,04/10/2023,04/08/2023,4,2,- -,1,- -,7,SIN INFORMACIÓN,24/11/2022,NaN,NaN,NaN,NaN,- -,DANIELA BURGOS,3128439725,20/02/2024,9000736458,NaN,NaN,NaN,Captura 1.6.31,GUNEIWIA,NaN,CRESPO,TORRES,CC,1148197258,5.0,1,NaN,0,40.0,6,6,1,3,2,"7,3",72,13,1.0,"14,1",-2.4425,2,"-0,5607",3,2,1,2,1,1,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO DE SALUD PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,20/02/2024,NaN,0
8,113,11/08/2023,32,2023,4400101060,1,ROYNER,CALETH,CAMBAR,GONZALEZ,RC,1124555656,11,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,WINPESHI,NaN,ROMANA-WIMPESHI,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,4,170,44,847,11/08/2023,11/08/2023,4,2,- -,1,- -,7,3234412269,28/11/2022,NaN,NaN,NaN,NaN,- -,CARLOS BENANIDEZ,3126112626,21/02/2024,9011820499,NaN,NaN,NaN,Captura 1.6.31,DELIA,VERONICA,CAMBAR,GONZALEZ,CC,6230981,1.0,0,NaN,0,25.0,6,6,1,1,1,"8,6",80,"12,5",1.0,"13,44",-2.4244,2,"4,2623",3,2,1,1,2,1,2,1,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,GRUPO IMB IPS SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,RIOHACHA,21/02/2024,NaN,0
15,113,18/06/2023,25,2023,4443000706,1,PAULA,ELENA,NAVARRO,EPIEYU,RC,1124092548,8,2,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,44,430,1,MAICAO,NaN,NaN,NaN,BARRIO LA PISTA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,430,18/06/2023,14/06/2023,4,1,18/06/2023,1,- -,7,3207322482,08/10/2022,NaN,NaN,NaN,NaN,- -,FRANKLIN MEDINA,3045023928,22/02/2024,90021149269,NaN,NaN,NaN,Captura 1.6.31,MARIA,ISABEL,EPIEYU,SILVA,CC,1124074484,1.0,1,3000.0,49,39.0,6,6,1,1,2,"5,8",65,11,1.0,"13,7",-2.2746,2,"-1,5855",2,2,1,2,2,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINICA DE ESPECIALISTAS GUAJIRA SA,COLOMBIA,GUAJIRA,MAICAO,COLOMBIA,GUAJIRA,MAICAO,GUAJIRA,MAICAO,22/02/2024,NaN,0
18,113,24/06/2023,25,2023,2057090000,85,MENDERSON,JOSE,TORRES,TORRES,RC,1063604249,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,YEWRWA,NaN,VEREDA YEWRWA,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,1,2.0,2,2,2,1,1,170,20,570,21/06/2023,01/06/2023,4,1,21/06/2023,1,- -,7,SIN INFORMACIÓN,02/08/2022,NaN,NaN,NaN,NaN,- -,SINDY KATHERINE CONRRADO TORRES,3176919370,21/02/2024,90001742165,NaN,NaN,NaN,Captura 1.6.31,SEYKUNEY,NaN,TORRES,RAMOS,CC,1149194667,1.0,1,2550.0,50,36.0,10,7,2,2,1,"4,2",58,13,1.0,"12,5",-3.1602,1,"-6,6879",1,2,1,2,2,2,2,1,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CRN CAMBIANDO VIDAS PUEBLO BELLO CESAR,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,21/02/2024,NaN,0
25,113,16/03/2023,11,2023,4400101132,1,JESUS,MANUEL,ALBERTO,PINTO,RC,1119416517,9,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,90,3,NaN,NaN,COMUNIDAD ARIMAKA,NaN,COMUNIDAD ARIMAKA,NaN,NaN,99999.07,S,EPSI01,1,WIWA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,90,16/03/2023,16/03/2023,4,1,16/03/2023,1,- -,7,3008790081,14/06/2022,NaN,NaN,NaN,NaN,- -,ALFREDO BARBOSA,3182014954,20/02/2024,9013367514,NaN,NaN,NaN,Captura 1.6.31,YULEIDI,NaN,PINTO,NaN,TI,10123419476,1.0,1,2500.0,45,40.0,6,6,2,2,2,"5,4",65,11,3.0,"12,8",-3.8059,1,"-3,1065",1,1,1,1,1,1,1,1,1.0,E43X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINIVIDA Y SALUD IPS SAS,COLOMBIA,GUAJIRA,DIBULLA,COLOMBIA,GUAJIRA,DIBULLA,GUAJIRA,RIOHACHA,20/02/2024,NaN,0
28,113,11/01/2024,50,2023,4443000277,1,JOSE,MANUEL,PUSHAINA,LOPEZ,RC,1243541139,11,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,430,3,NaN,NaN,RANCHERIA ULAY,NaN,RANCHERIA ULAY,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,430,12/12/2023,12/12/2023,4,1,12/12/2023,1,- -,0,3177311279,18/01/2023,NaN,NaN,NaN,NaN,- -,LEIDA UTRIA SISSIV[1000000C00],3002756893,11/01/2024,8921201151,NaN,NaN,NaN,Captura 1.6.31,LESBIA,NaN,LOPEZ,URIANA,CC,1124060233,1.0,1,NaN,0,NaN,11,8,2,3,2,46,61,11,NaN,"123,6",17.2444,7,"-5,8123",1,2,2,2,2,1,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL SAN JOSE DE MAICAO,COLOMBIA,GUAJIRA,MAICAO,COLOMBIA,GUAJIRA,MAICAO,GUAJIRA,MAICAO,11/01/2024,NaN,0
38,113,17/08/2023,33,2023,4400100137,1,JEIDER,JADED,URIANA,DUARTE,RC,1244480653,8,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,1,3,NaN,NaN,LA ESPERANZA,NaN,KM 12 VIA RIOHACHA VALLEDUPAR,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,4,170,44,1,17/08/2023,17/08/2023,4,2,- -,1,- -,0,3218949132,15/06/2023,NaN,NaN,NaN,NaN,- -,EQUIPO ATENCION INDIVIDUAL INTEGRAL RESOLUCION...,3008119298,08/03/2024,892115009,NaN,NaN,NaN,Captura 1.6.31,CLARA,BRIGHITH,DUARTE,NaN,AS,99293558943,1.0,3,2900.0,49,38.0,8,4,2,1,2,"4,7",60,12,1.0,"13,1",-3.0366,1,"0,7874",3,2,1,1,2,2,1,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL NUESTRA SEÑORA DE LOS REMEDIOS,COLOMBIA,GUAJIRA,RIOHACHA,COLOMBIA,GUAJIRA,RIOHACHA,GUAJIRA,RIOHACHA,08/03/2024,NaN,0
52,113,26/06/2023,25,2023,4700100508,0,DWINAWIN,NaN,VILLAFAÑE,IZQUIERDO,RC,1083066054,6,2,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,47,1,3,NaN,NaN,SIERRA NEVEDA,NaN,SIERRA NEVEDA DE SANTA MARTA,0.0,0.0,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,47,1,23/06/2023,23/06/2023,4,1,23/06/2023,1,- -,6,31027486222,30/11/2022,NaN,NaN,4.700101e+11,SOCIEDAD MEDICA DE SANTA MARTA SAS,02/04/2024,ROXANA FONTALVO,3107279735,27/03/2024,8917016641,NaN,NaN,NaN,SIVIGILA - 2018 -18.6.5$0$0.0,GUNKEIWIA,NaN,IZQUIERDO,VILLAFAÑE,CC,1148198211,5.0,0,0.0,0,0.0,0,0,2,2,2,"6,6",59,0,3.0,"18,96",1.7156,5,"-2,9699",1,1,2,2,1,1,2,1,NaN,NaN,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,SOCIEDAD MEDICA SANTA MARTA SAS CLINICA PRADO,COLOMBIA,MAGDALENA,SANTA MARTA,COLOMBIA,MAGDALENA,SANTA MARTA,MAGDALENA,SANTA MARTA,02/04/2024,NaN,0
59,113,28/12/2023,52,2023,2057000236,1,HIJO DE ANA,LUCIA,VILLAFAÑE,ARROYO,MS,20570I0037,13,3,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,VEREDA NUEVO COLON,NaN,VEREDA NUEVO COLON,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,28/12/2023,27/12/2023,4,2,- -,1,- -,6,SIN INFORMACIÓN,19/12/2023,NaN,NaN,NaN,NaN,- -,JOSE RUIZ OSORIO,3206803926,25/01/2024,8240026728,NaN,NaN,NaN,Captura 1.6.31,ANA,LUCIA,VILLAFAÑE,ARROYO,CC,1007582003,5.0,4,NaN,0,39.0,0,0,2,2,2,"3,5",53,0,3.0,"12,5",-1.5876,3,"1,6459",3,2,1,2,2,2,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,ESE HOSPITAL CAMILO VILLAZON PUMAREJO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,25/01/2024,NaN,0
72,113,09/05/2023,19,2023,4484700836,1,NAHUM,MANUEL,MONTIEL,GONZALEZ,RC,1124557417,9,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA ATOUYAKA,NaN,RANCHERIA ATOUYAKA,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,09/05/2023,05/05/2023,4,1,09/05/2023,1,- -,7,3113090972,15/07/2022,NaN,NaN,NaN,NaN,- -,CARLOS MEJIA,3182049520,21/02/2024,900492815,NaN,NaN,NaN,Captura 1.6.31,GIELANGIE,PAULINA,MONTIEL,GONZALEZ,DE,VEN27931806,1.0,1,3170.0,54,39.0,6,7,1,1,1,"6,9",70,14,1.0,"14,1",-2.5103,2,"-0,8776",3,2,1,1,2,2,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,21/02/2024,NaN,0
75,113,26/05/2023,21,2023,4400101132,1,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA MAPUACHON,NaN,RANCHERIA MAPUACHON,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,26/05/2023,26/05/2023,4,1,26/05/2023,1,- -,7,3207300791,29/06/2022,NaN,NaN,NaN,NaN,- -,ALDAIR MEJIA,3225366812,20/02/2024,9013367514,NaN,NaN,NaN,Captura 1.6.31,MAGALI,BELLI,IPUANA,GONZALEZ,CC,27033702,5.0,1,2620.0,47,37.0,5,6,1,1,1,"6,2","66,5",14,1.0,14,-2.6054,2,"-2,9678",1,2,1,1,2,2,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CLINIVIDA Y SALUD IPS SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,RIOHACHA,20/02/2024,NaN,0
76,113,26/05/2023,21,2023,4484700677,2,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA MAPUACHON,NaN,RANCHERIA MAPUACHON,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,26/05/2023,26/05/2023,4,1,26/05/2023,1,- -,7,3207300791,29/06/2022,NaN,NaN,NaN,NaN,- -,ALDAIR MEJIA,3225366812,20/02/2024,9001913221,NaN,NaN,NaN,Captura 1.6.31,MAGALI,BELLI,GONZALEZ,IPUANA,CC,27033702,5.0,1,2620.0,47,38.0,10,4,1,1,1,"6,15","65,6","12,8",3.0,"14,3",-2.3008,2,"-3,3617",1,2,2,2,2,2,2,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,OUTTAJIAPULEE IPSI,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
90,113,30/10/2023,44,2023,2004500012,14,MARIANA,SOFIA,CAPITAN,CAPITAN,RC,1062819862,11,2,170,COLOMBIA,F,NaN,NaN,NaN,NaN,170,20,45,3,NaN,NaN,LA MISION,NaN,LA MISION,NaN,NaN,99999.07,S,EPSI01,1,YUKPA,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,45,30/10/2023,30/10/2023,4,2,- -,1,- -,7,SIN INFORMACIÓN,01/11/2022,NaN,NaN,NaN,NaN,- -,LAURA VANESA ARRIETA OSPINO,3015694979,26/02/2024,8240023621,NaN,NaN,NaN,Captura 1.6.31,PATRICIA,NaN,CAPITAN,BARRETO,CC,1003039938,5.0,2,NaN,0,40.0,11,6,2,3,2,"6,4",68,"11,5",1.0,"13,8",-2.1768,2,"-1,8927",2,2,1,1,2,1,2,1,2.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,DUSAKAWI IPS BECERRIL UNIDAD MOVIL,COLOMBIA,CESAR,BECERRIL,COLOMBIA,CESAR,BECERRIL,CESAR,BECERRIL,26/02/2024,NaN,0
95,113,26/05/2023,21,2023,4484700836,1,ELIENDER,SEGUNDO,IPUANA,GONZALEZ,RC,1124557354,10,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,44,847,3,NaN,NaN,RANCHERIA MAPUACHON,NaN,RANCHERIA MAPUACHON,NaN,NaN,99999.07,S,EPSI01,1,WAYUU,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,44,847,26/05/2023,24/05/2023,4,1,26/05/2023,1,- -,7,3207300791,29/06/2022,NaN,NaN,NaN,NaN,- -,CARLOS MEJIA QUINTANA,3182049520,20/02/2024,900492815,NaN,NaN,NaN,Captura 1.6.31,MAGALY,BELLI,IPUANA,GONZALEZ,CC,27033702,5.0,2,2620.0,47,37.0,5,6,1,1,1,"6,2","66,5",14,1.0,14,-2.6054,2,"-2,9678",1,2,1,1,2,1,1,1,1.0,E440,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,UNIDAD MATERNO INFANTIL TALAPUIN SAS,COLOMBIA,GUAJIRA,URIBIA,COLOMBIA,GUAJIRA,URIBIA,GUAJIRA,URIBIA,20/02/2024,NaN,0
104,113,04/09/2023,36,2023,2057000983,5,DUKARIN,NaN,MARQUEZ,MARQUEZ,MS,20570I0049,9,2,170,COLOMBIA,M,NaN,NaN,NaN,NaN,170,20,570,3,NaN,NaN,NABUSIMAKE,NaN,NABUSIMAKE - PARAGAKA,NaN,NaN,99999.07,S,EPSI01,1,ARHUACO,1.0,2,2,2,2,2.0,NaN,2,2,2.0,2,2,2,1,1,170,20,570,04/09/2023,20/08/2023,4,2,- -,1,- -,0,SIN INFORMACIÓN,01/06/2023,NaN,NaN,NaN,NaN,- -,ZARAN ROBLES,3155162045,11/03/2024,9000736458,NaN,NaN,NaN,Captura 1.6.31,ZARKUN,NaN,MARQUEZ,ALVAREZ,CC,1151199296,5.0,0,NaN,0,40.0,3,0,2,2,2,"4,2",55,0,3.0,"13,9",-0.9362,4,"-3,1448",1,1,2,1,2,2,1,1,2.0,E40X,NaN,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,CENTRO DE SALUD PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,COLOMBIA,CESAR,PUEBLO BELLO,CESAR,PUEBLO BELLO,11/03/2024,NaN,0

### Revisar consistencia clas_peso vs zscore

In [7]:
data2023.groupby("clas_peso")["zscore_pt"].describe()

,count,mean,std,min,25%,50%,75%,max
clas_peso,,,,,,,,
1,14.0,-3.823543,0.672357,-5.2786,-4.040900,-3.69400,-3.333750,-3.0366
2,66.0,-2.408103,0.250499,-2.9910,-2.526000,-2.37765,-2.207775,-2.0297
3,11.0,-1.625573,0.221141,-1.9727,-1.799750,-1.63360,-1.423050,-1.2858
4,10.0,-0.298230,0.590471,-0.9999,-0.754900,-0.46180,0.086600,0.7653
5,3.0,1.734100,0.255253,1.4886,1.602100,1.71560,1.856850,1.9981
6,1.0,2.516400,NaN,2.5164,2.516400,2.51640,2.516400,2.5164
7,2.0,16.726150,0.732916,16.2079,16.467025,16.72615,16.985275,17.2444

### Detectar outliers

In [8]:
cols = ["peso_act", "talla_act", "imc"]

for col in cols:
    data2023[col] = data2023[col].astype(str).str.replace(",", ".")
    data2023[col] = pd.to_numeric(data2023[col], errors="coerce")
    
data2023[["peso_act", "talla_act", "imc"]].describe()

         peso_act   talla_act         imc
count  107.000000  107.000000  107.000000
mean     7.612617   70.724299   15.583084
std      4.560459   10.136240   13.482289
min      2.300000   45.000000   10.000000
25%      5.800000   65.000000   13.100000
50%      7.100000   71.500000   13.700000
75%      8.250000   76.250000   14.135000
max     46.000000   98.500000  123.600000

### Revisar duplicados

In [9]:
data2023.duplicated().sum()

np.int64(0)

### Revisar valores negativos o raros

In [10]:
data2023["peso_act"] = data2023["peso_act"].astype(str).str.replace(",", ".")
data2023["peso_act"] = pd.to_numeric(data2023["peso_act"], errors="coerce")
data2023[data2023["peso_act"] <= 0]
data2023["peso_act"].dtype

dtype('float64')

### Revisar columnas completamente vacías

In [11]:
data2023.isnull().sum().sort_values(ascending=False).head(10)

otra_ident                       107
otra_orien                       107
sem_ges_                         107
fm_grado                         107
cbmte_                           107
cer_def_                         107
fm_unidad                        107
estrato_datos_complementarios    107
RegIniFec                        107
fm_fuerza                        107
dtype: int64